version: 2
updates:
  # Dependensi npm/pnpm (membaca pnpm-lock.yaml)
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels: ['dependencies']
    commit-message:
      prefix: 'chore'
      include: scope

  # Update versi action di workflow CI
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    labels: ['dependencies', 'ci']
    commit-message:
      prefix: 'chore'
      include: scope
